name: Atualizar Agenda Studio Clean

on:
  schedule:
    - cron: '0 11,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas necessárias
        run: |
          pip install requests pandas gspread google-auth

      - name: Rodar o script de atualização
        run: |
          python studio_clean_sync_3.py
        env:
          MEU_EMAIL: ${{ secrets.MEU_EMAIL }}
          SENHA_APP: ${{ secrets.SENHA_APP }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          PYTHONUNBUFFERED: '1'

